"""Generate the pages derived from data/ and governance.toml: the Concepts, Notation, Constants and
Moderators and Curators appendices, the living review table in building-alan/index.qmd and the
links to the other languages in _quarto.yml. tools/edition.py writes the same pages in each
language (decision 0014).

    python3 tools/generate.py           write the pages (Quarto runs this before every render)
    python3 tools/generate.py --check   exit 1 if a generated page is out of date or the data is invalid
"""

from __future__ import annotations

import datetime as dt
import json
import math
import os
import re
import sys
import unicodedata
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import book  # noqa: E402
import i18n  # noqa: E402

HEADER = "<!-- Generated by tools/generate.py from {source}. Do not edit by hand. -->"
ID_PATTERN = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
CONCEPT_LINK = re.compile(r"(?:concepts\.qmd#|@)sec-concept-([a-z0-9-]+)")
LIVING_REVIEW_BEGIN = "<!-- BEGIN generated: living reviews -->"
LIVING_REVIEW_END = "<!-- END generated: living reviews -->"
LANGUAGES_BEGIN = "# BEGIN generated: languages"
LANGUAGES_END = "# END generated: languages"


def relative(from_page: str, to_page: str) -> str:
    return os.path.relpath(book.ROOT / to_page, (book.ROOT / from_page).parent)


def validate(concepts, notation, constants, metrics, technologies, keys, pages) -> list[str]:
    errors: list[str] = []

    def unique_ids(items, source):
        seen = set()
        for item in items:
            item_id = item.get("id", "")
            if not ID_PATTERN.match(item_id):
                errors.append(f"{source}: invalid id {item_id!r} (lowercase words joined by hyphens)")
            if item_id in seen:
                errors.append(f"{source}: duplicate id {item_id!r}")
            seen.add(item_id)
        return seen

    concept_ids = unique_ids(concepts, "data/concepts.toml")
    unique_ids(notation, "data/notation.toml")
    unique_ids(constants, "data/constants.toml")

    for concept in concepts:
        for required in ("term", "short", "definition"):
            if not str(concept.get(required, "")).strip():
                errors.append(f"data/concepts.toml: {concept.get('id')} has no {required}")
        for related in concept.get("related", []):
            if related not in concept_ids:
                errors.append(f"data/concepts.toml: {concept['id']} relates to unknown concept {related!r}")
        for key in concept.get("references", []):
            if key not in keys:
                errors.append(f"data/concepts.toml: {concept['id']} cites {key!r}, not in references.bib")

    for constant in constants:
        if not constant.get("exact") and "uncertainty" not in constant:
            errors.append(f"data/constants.toml: {constant['id']} is not exact and has no uncertainty")

    metric_names = {metric["name"] for metric in metrics}
    for tech_id, (path, tech) in technologies.items():
        source = f"data/technologies/{path.name}"
        if tech.get("id") != tech_id:
            errors.append(f"{source}: id must be {tech_id!r}, the file name")
        for metric in tech.get("metric", []):
            name = metric.get("name")
            if name not in metric_names:
                errors.append(f"{source}: unknown metric {name!r} (add it to data/metrics.toml)")
            for required in ("value", "unit", "as_of", "source"):
                if required not in metric:
                    errors.append(f"{source}: metric {name!r} has no {required}")
            if metric.get("source") and metric["source"] not in keys:
                errors.append(f"{source}: metric {name!r} cites {metric['source']!r}, not in references.bib")
            try:
                dt.date.fromisoformat(str(metric.get("as_of", "")))
            except ValueError:
                errors.append(f"{source}: metric {name!r} has as_of {metric.get('as_of')!r}, not YYYY-MM-DD")

    for page in pages:
        if page.path in book.GENERATED_PAGES:
            continue
        for concept_id in CONCEPT_LINK.findall(book.strip_code_and_comments(page.body)):
            if concept_id not in concept_ids:
                errors.append(f"{page.path}: links to unknown concept {concept_id!r}")
    return errors


def concept_usage(pages) -> dict[str, list]:
    usage: dict[str, list] = {}
    for page in pages:
        if page.path in book.GENERATED_PAGES:
            continue
        for concept_id in dict.fromkeys(CONCEPT_LINK.findall(book.strip_code_and_comments(page.body))):
            usage.setdefault(concept_id, []).append(page)
    return usage


def sort_key(text: str) -> str:
    """Alphabetical order in any language: accents do not move a word to the end."""
    return "".join(c for c in unicodedata.normalize("NFKD", text.lower()) if not unicodedata.combining(c))


def concepts_page(concepts, pages, lang=None) -> str:
    target = "appendices/concepts.qmd"
    words = i18n.strings(lang)["pages"]
    by_id = {concept["id"]: concept for concept in concepts}
    usage = concept_usage(pages)
    lines = [
        f"# {words['concepts_title']} {{#sec-concepts}}",
        "",
        HEADER.format(source="data/concepts.toml"),
        "",
        words["concepts_intro"],
        "",
    ]
    for concept in sorted(concepts, key=lambda c: sort_key(c["term"])):
        lines += [f"## {concept['term']} {{#sec-concept-{concept['id']} .unnumbered}}", ""]
        lines += [" ".join(concept["definition"].split()), ""]
        related = [by_id[r] for r in concept.get("related", [])]
        if related:
            links = ", ".join(f"[{r['term']}](#sec-concept-{r['id']})" for r in related)
            lines += [f"**{words['related']}:** {links}", ""]
        if concept.get("references"):
            cites = "; ".join(f"@{key}" for key in concept["references"])
            lines += [f"**{words['references']}:** [{cites}]", ""]
        used = usage.get(concept["id"], [])
        if used:
            links = ", ".join(f"[{i18n.page_title(lang, p)}]({relative(target, p.path)})" for p in used)
            lines += [f"**{words['used_in']}:** {links}", ""]
    return "\n".join(lines).rstrip() + "\n"


def notation_page(notation, lang=None) -> str:
    words = i18n.strings(lang)["pages"]
    lines = [
        f"# {words['notation_title']} {{#sec-notation}}",
        "",
        HEADER.format(source="data/notation.toml"),
        "",
        words["notation_intro"],
        "",
        words["notation_header"],
        "|---|---|---|",
    ]
    for symbol in notation:
        lines.append(f"| {symbol['symbol']} | {symbol['meaning']} | {symbol.get('unit', '')} |")
    return "\n".join(lines) + "\n"


def scientific(value, uncertainty=None) -> str:
    """LaTeX for a number. With an uncertainty, keep the digits down to its second significant one."""
    if isinstance(value, int):
        return f"${value}$"
    if not uncertainty:
        mantissa, _, exponent = repr(value).partition("e")
        return f"${mantissa} \\times 10^{{{int(exponent)}}}$" if exponent else f"${mantissa}$"
    exponent = math.floor(math.log10(abs(value)))
    decimals = max(exponent - math.floor(math.log10(uncertainty)) + 1, 0)
    mantissa = f"{value / 10**exponent:.{decimals}f}"
    return f"${mantissa} \\times 10^{{{exponent}}}$" if exponent else f"${mantissa}$"


def constants_page(constants, lang=None) -> str:
    strings = i18n.strings(lang)
    words = strings["pages"]
    lines = [
        f"# {words['constants_title']} {{#sec-constants}}",
        "",
        HEADER.format(source="data/constants.toml"),
        "",
        words["constants_intro"],
        "",
        words["constants_header"],
        "|---|---|---|---|---|---|",
    ]
    for constant in constants:
        uncertainty = words["exact"] if constant.get("exact") else scientific(constant["uncertainty"])
        value = scientific(constant["value"], constant.get("uncertainty"))
        lines.append(
            f"| {constant['name']} | {constant['symbol']} | {i18n.decimal(value, strings['decimal'])} "
            f"| {constant['unit']} | {i18n.decimal(uncertainty, strings['decimal'])} | {constant['source']} |"
        )
    return "\n".join(lines) + "\n"


def review_due(last_reviewed, not_reviewed="not reviewed yet") -> str:
    if not last_reviewed:
        return not_reviewed
    date = dt.date.fromisoformat(str(last_reviewed))
    try:
        return date.replace(year=date.year + 1).isoformat()
    except ValueError:  # 29 February
        return date.replace(year=date.year + 1, day=28).isoformat()


def people(handles, none_yet="none yet") -> str:
    """GitHub handles as profile links. Written without @, which Quarto reads as a citation."""
    found = [h for h in handles if isinstance(h, str) and book.GITHUB_HANDLE.match(h)] if isinstance(handles, list) else []
    return ", ".join(f"[{name}](https://github.com/{name})" for name in found) or none_yet


def people_page(pages, lang=None) -> str:
    target = "appendices/people.qmd"
    strings = i18n.strings(lang)
    words = strings["pages"]
    none_yet = words["none_yet"]
    moderators = book.part_moderators()
    lines = [
        f"# {words['people_title']} {{#sec-people}}",
        "",
        HEADER.format(source="governance.toml, i18n/languages.toml and the front matter of each page"),
        "",
        words["people_intro"].format(governance=book.governance_url()),
        "",
        f"## {words['maintainers']} {{.unnumbered}}",
        "",
        people(book.maintainers(), none_yet),
        "",
        f"## {words['moderators']} {{.unnumbered}}",
        "",
        words["moderators_header"],
        "|---|---|",
    ]
    for title in dict.fromkeys(page.part for page in pages if page.part):
        lines.append(f"| {strings['parts'].get(title, title)} | {people(moderators.get(title, []), none_yet)} |")
    lines += ["", f"## {words['curators']} {{.unnumbered}}", ""]
    curated = [page for page in pages if isinstance(page.meta.get("curators"), list) and page.meta["curators"]]
    if curated:
        lines += [words["curators_header"], "|---|---|---|"]
        for page in curated:
            part = strings["parts"].get(page.part, page.part) if page.part else ""
            title = i18n.page_title(lang, page)
            lines.append(f"| [{title}]({relative(target, page.path)}) | {part} | {people(page.meta['curators'], none_yet)} |")
    else:
        lines.append(words["no_curator"])
    lines += [
        "",
        f"## {words['translators']} {{.unnumbered}}",
        "",
        words["translators_intro"].format(translating=book.repo_url() + "/blob/main/docs/translating.md"),
        "",
    ]
    registered = list(i18n.languages().values())
    if registered:
        lines += [words["translators_header"], "|---|---|---|"]
        for language in registered:
            name = language.english_name if lang is None else language.name
            lines.append(
                f"| {name} | {people(language.maintainers, none_yet)} | {people(i18n.reviewers(language.id), none_yet)} |"
            )
    else:
        lines.append(words["no_language"])
    return "\n".join(lines) + "\n"


def living_review_table(pages, lang=None) -> str:
    target = "building-alan/index.qmd"
    strings = i18n.strings(lang)
    words = strings["pages"]
    lines = [
        LIVING_REVIEW_BEGIN,
        "",
        words["living_review_header"],
        "|---|---|---|---|---|",
    ]
    for page in pages:
        if page.kind != "living-review":
            continue
        last = page.meta.get("last_reviewed") or words["never"]
        status = page.meta.get("status", "")
        due = review_due(page.meta.get("last_reviewed"), words["not_reviewed"])
        lines.append(
            f"| [{i18n.page_title(lang, page)}]({relative(target, page.path)}) | {strings['status'].get(status, status)} "
            f"| {last} | {due} | {people(page.meta.get('curators'), words['none_yet'])} |"
        )
    lines += ["", LIVING_REVIEW_END]
    return "\n".join(lines)


def building_alan_index(pages, text: str | None = None, lang=None) -> str | None:
    """building-alan/index.qmd, or the text given (its translation), with the table rewritten."""
    path = book.ROOT / "building-alan" / "index.qmd"
    if text is None:
        if not path.exists():
            return None
        text = path.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(LIVING_REVIEW_BEGIN) + r".*?" + re.escape(LIVING_REVIEW_END), re.S)
    if not pattern.search(text):
        return text
    return pattern.sub(lambda _: living_review_table(pages, lang), text)


def language_links(lang=None) -> list[str]:
    """The sidebar links of an edition to the others, in _quarto.yml. The translate icon marks them,
    and i18n/language-link.html points each at the same page in the other edition."""
    others = [(None, i18n.strings(None))] if lang else []
    others += [(language.id, i18n.strings(language.id)) for language in i18n.published() if language.id != lang]
    lines = []
    for other, strings in others:
        label = json.dumps(strings["edition"]["link"], ensure_ascii=False)
        lines += [
            "      - icon: translate",
            f"        href: {i18n.edition_url(other)}",
            f"        text: {label}",
            f"        aria-label: {label}",
        ]
    return lines


def quarto_yml(text: str | None = None, lang=None) -> str | None:
    """_quarto.yml, or the text given (an edition's copy), with the language links rewritten."""
    if text is None:
        if not book.QUARTO_YML.exists():
            return None
        text = book.QUARTO_YML.read_text(encoding="utf-8")
    pattern = re.compile(r"^([ \t]*)" + re.escape(LANGUAGES_BEGIN) + r"\n.*?^[ \t]*" + re.escape(LANGUAGES_END) + r"$", re.S | re.M)
    match = pattern.search(text)
    if not match:
        return text
    indent = match.group(1)
    block = "\n".join([indent + LANGUAGES_BEGIN, *language_links(lang), indent + LANGUAGES_END])
    return text[: match.start()] + block + text[match.end() :]


def outputs() -> tuple[dict[str, str], list[str]]:
    pages = book.pages()
    concepts = book.load_data("concepts.toml").get("concept", [])
    notation = book.load_data("notation.toml").get("symbol", [])
    constants = book.load_data("constants.toml").get("constant", [])
    metrics = book.load_data("metrics.toml").get("metric", [])
    errors = validate(concepts, notation, constants, metrics, book.technologies(), book.bib_keys(), pages)
    files = {
        "appendices/concepts.qmd": concepts_page(concepts, pages),
        "appendices/notation.qmd": notation_page(notation),
        "appendices/constants.qmd": constants_page(constants),
        "appendices/people.qmd": people_page(pages),
    }
    index = building_alan_index(pages)
    if index is not None:
        files["building-alan/index.qmd"] = index
    config = quarto_yml()
    if config is not None:
        files["_quarto.yml"] = config
    return files, errors


def translated_outputs(lang: str) -> tuple[dict[str, str], dict[str, list]]:
    """The generated appendices of an edition, from the data overlays of its language, and the
    state of each translated text by source file. tools/edition.py writes them into its copy."""
    pages = book.pages()
    data, states = {}, {}
    for source, english in i18n.sources().items():
        data[source], states[source] = i18n.translate(lang, source, english)
    files = {
        "appendices/concepts.qmd": concepts_page(data["data/concepts.toml"].get("concept", []), pages, lang),
        "appendices/notation.qmd": notation_page(data["data/notation.toml"].get("symbol", []), lang),
        "appendices/constants.qmd": constants_page(data["data/constants.toml"].get("constant", []), lang),
        "appendices/people.qmd": people_page(pages, lang),
    }
    return files, states


def main(argv: list[str]) -> int:
    check = "--check" in argv
    files, errors = outputs()
    for error in errors:
        print(f"error: {error}", file=sys.stderr)
    stale = []
    for relative_path, content in files.items():
        path = book.ROOT / relative_path
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if check:
            stale.append(relative_path)
        else:
            path.write_text(content, encoding="utf-8")
            print(f"wrote {relative_path}")
    for relative_path in stale:
        print(f"error: {relative_path} is out of date; run python3 tools/generate.py", file=sys.stderr)
    return 1 if errors or stale else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
