"""Generate the pages derived from data/ and governance.toml: the Concepts, Notation, Constants and
Moderators and Curators appendices, and the dossier table in building-alan/index.qmd.

    python3 tools/generate.py           write the pages (Quarto runs this before every render)
    python3 tools/generate.py --check   exit 1 if a generated page is out of date or the data is invalid
"""

from __future__ import annotations

import datetime as dt
import math
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import book  # noqa: E402

HEADER = "<!-- Generated by tools/generate.py from {source}. Do not edit by hand. -->"
ID_PATTERN = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
CONCEPT_LINK = re.compile(r"(?:concepts\.qmd#|@)sec-concept-([a-z0-9-]+)")
DOSSIER_BEGIN = "<!-- BEGIN generated: dossiers -->"
DOSSIER_END = "<!-- END generated: dossiers -->"


def relative(from_page: str, to_page: str) -> str:
    return os.path.relpath(book.ROOT / to_page, (book.ROOT / from_page).parent)


def validate(concepts, notation, constants, metrics, technologies, keys, pages) -> list[str]:
    errors: list[str] = []

    def unique_ids(items, source):
        seen = set()
        for item in items:
            item_id = item.get("id", "")
            if not ID_PATTERN.match(item_id):
                errors.append(f"{source}: invalid id {item_id!r} (lowercase words joined by hyphens)")
            if item_id in seen:
                errors.append(f"{source}: duplicate id {item_id!r}")
            seen.add(item_id)
        return seen

    concept_ids = unique_ids(concepts, "data/concepts.toml")
    unique_ids(notation, "data/notation.toml")
    unique_ids(constants, "data/constants.toml")

    for concept in concepts:
        for required in ("term", "short", "definition"):
            if not str(concept.get(required, "")).strip():
                errors.append(f"data/concepts.toml: {concept.get('id')} has no {required}")
        for related in concept.get("related", []):
            if related not in concept_ids:
                errors.append(f"data/concepts.toml: {concept['id']} relates to unknown concept {related!r}")
        for key in concept.get("references", []):
            if key not in keys:
                errors.append(f"data/concepts.toml: {concept['id']} cites {key!r}, not in references.bib")

    for constant in constants:
        if not constant.get("exact") and "uncertainty" not in constant:
            errors.append(f"data/constants.toml: {constant['id']} is not exact and has no uncertainty")

    metric_names = {metric["name"] for metric in metrics}
    for tech_id, (path, tech) in technologies.items():
        source = f"data/technologies/{path.name}"
        if tech.get("id") != tech_id:
            errors.append(f"{source}: id must be {tech_id!r}, the file name")
        for metric in tech.get("metric", []):
            name = metric.get("name")
            if name not in metric_names:
                errors.append(f"{source}: unknown metric {name!r} (add it to data/metrics.toml)")
            for required in ("value", "unit", "as_of", "source"):
                if required not in metric:
                    errors.append(f"{source}: metric {name!r} has no {required}")
            if metric.get("source") and metric["source"] not in keys:
                errors.append(f"{source}: metric {name!r} cites {metric['source']!r}, not in references.bib")
            try:
                dt.date.fromisoformat(str(metric.get("as_of", "")))
            except ValueError:
                errors.append(f"{source}: metric {name!r} has as_of {metric.get('as_of')!r}, not YYYY-MM-DD")

    for page in pages:
        if page.path in book.GENERATED_PAGES:
            continue
        for concept_id in CONCEPT_LINK.findall(book.strip_code_and_comments(page.body)):
            if concept_id not in concept_ids:
                errors.append(f"{page.path}: links to unknown concept {concept_id!r}")
    return errors


def concept_usage(pages) -> dict[str, list]:
    usage: dict[str, list] = {}
    for page in pages:
        if page.path in book.GENERATED_PAGES:
            continue
        for concept_id in dict.fromkeys(CONCEPT_LINK.findall(book.strip_code_and_comments(page.body))):
            usage.setdefault(concept_id, []).append(page)
    return usage


def concepts_page(concepts, pages) -> str:
    target = "appendices/concepts.qmd"
    by_id = {concept["id"]: concept for concept in concepts}
    usage = concept_usage(pages)
    lines = [
        "# Concepts {#sec-concepts}",
        "",
        HEADER.format(source="data/concepts.toml"),
        "",
        "Every technical term the book uses, in plain language. Each entry lists the pages that use it.",
        "",
    ]
    for concept in sorted(concepts, key=lambda c: c["term"].lower()):
        lines += [f"## {concept['term']} {{#sec-concept-{concept['id']} .unnumbered}}", ""]
        lines += [" ".join(concept["definition"].split()), ""]
        related = [by_id[r] for r in concept.get("related", [])]
        if related:
            links = ", ".join(f"[{r['term']}](#sec-concept-{r['id']})" for r in related)
            lines += [f"**Related:** {links}", ""]
        if concept.get("references"):
            cites = "; ".join(f"@{key}" for key in concept["references"])
            lines += [f"**References:** [{cites}]", ""]
        used = usage.get(concept["id"], [])
        if used:
            links = ", ".join(f"[{p.title}]({relative(target, p.path)})" for p in used)
            lines += [f"**Used in:** {links}", ""]
    return "\n".join(lines).rstrip() + "\n"


def notation_page(notation) -> str:
    lines = [
        "# Notation {#sec-notation}",
        "",
        HEADER.format(source="data/notation.toml"),
        "",
        "Every symbol keeps the same meaning across the whole book.",
        "",
        "| Symbol | Meaning | Unit |",
        "|---|---|---|",
    ]
    for symbol in notation:
        lines.append(f"| {symbol['symbol']} | {symbol['meaning']} | {symbol.get('unit', '')} |")
    return "\n".join(lines) + "\n"


def scientific(value, uncertainty=None) -> str:
    """LaTeX for a number. With an uncertainty, keep the digits down to its second significant one."""
    if isinstance(value, int):
        return f"${value}$"
    if not uncertainty:
        mantissa, _, exponent = repr(value).partition("e")
        return f"${mantissa} \\times 10^{{{int(exponent)}}}$" if exponent else f"${mantissa}$"
    exponent = math.floor(math.log10(abs(value)))
    decimals = max(exponent - math.floor(math.log10(uncertainty)) + 1, 0)
    mantissa = f"{value / 10**exponent:.{decimals}f}"
    return f"${mantissa} \\times 10^{{{exponent}}}$" if exponent else f"${mantissa}$"


def constants_page(constants) -> str:
    lines = [
        "# Constants {#sec-constants}",
        "",
        HEADER.format(source="data/constants.toml"),
        "",
        "Values from the 2019 revision of the SI, where the constant is exact by definition, and from",
        "CODATA otherwise.",
        "",
        "| Constant | Symbol | Value | Unit | Standard uncertainty | Source |",
        "|---|---|---|---|---|---|",
    ]
    for constant in constants:
        uncertainty = "exact" if constant.get("exact") else scientific(constant["uncertainty"])
        lines.append(
            f"| {constant['name']} | {constant['symbol']} | {scientific(constant['value'], constant.get('uncertainty'))} "
            f"| {constant['unit']} | {uncertainty} | {constant['source']} |"
        )
    return "\n".join(lines) + "\n"


def review_due(last_reviewed) -> str:
    if not last_reviewed:
        return "not reviewed yet"
    date = dt.date.fromisoformat(str(last_reviewed))
    try:
        return date.replace(year=date.year + 1).isoformat()
    except ValueError:  # 29 February
        return date.replace(year=date.year + 1, day=28).isoformat()


def people(handles) -> str:
    """GitHub handles as profile links. Written without @, which Quarto reads as a citation."""
    found = [h for h in handles if isinstance(h, str) and book.GITHUB_HANDLE.match(h)] if isinstance(handles, list) else []
    return ", ".join(f"[{name}](https://github.com/{name})" for name in found) or "none yet"


def people_page(pages) -> str:
    target = "appendices/people.qmd"
    moderators = book.part_moderators()
    lines = [
        "# Moderators and Curators {#sec-people}",
        "",
        HEADER.format(source="governance.toml and the front matter of each page"),
        "",
        "The people who look after the book. Maintainers look after the whole repository. Moderators",
        "look after a part: they review the changes to its pages and triage its issues. Curators look",
        "after single pages and review their dossiers. People are named by their GitHub handle. How the",
        f"roles work, and how to take one, is in [GOVERNANCE.md]({book.governance_url()}).",
        "",
        "## Maintainers {.unnumbered}",
        "",
        people(book.maintainers()),
        "",
        "## Moderators {.unnumbered}",
        "",
        "| Part | Moderators |",
        "|---|---|",
    ]
    for title in dict.fromkeys(page.part for page in pages if page.part):
        lines.append(f"| {title} | {people(moderators.get(title, []))} |")
    lines += ["", "## Curators {.unnumbered}", ""]
    curated = [page for page in pages if isinstance(page.meta.get("curators"), list) and page.meta["curators"]]
    if curated:
        lines += ["| Page | Part | Curators |", "|---|---|---|"]
        for page in curated:
            lines.append(f"| [{page.title}]({relative(target, page.path)}) | {page.part or ''} | {people(page.meta['curators'])} |")
    else:
        lines.append("No page has a curator yet.")
    return "\n".join(lines) + "\n"


def dossier_table(pages) -> str:
    target = "building-alan/index.qmd"
    lines = [
        DOSSIER_BEGIN,
        "",
        "| Dossier | Status | Last reviewed | Review due | Curators |",
        "|---|---|---|---|---|",
    ]
    for page in pages:
        if page.kind != "dossier":
            continue
        last = page.meta.get("last_reviewed") or "never"
        lines.append(
            f"| [{page.title}]({relative(target, page.path)}) | {page.meta.get('status', '')} "
            f"| {last} | {review_due(page.meta.get('last_reviewed'))} | {people(page.meta.get('curators'))} |"
        )
    lines += ["", DOSSIER_END]
    return "\n".join(lines)


def building_alan_index(pages) -> str | None:
    path = book.ROOT / "building-alan" / "index.qmd"
    if not path.exists():
        return None
    text = path.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(DOSSIER_BEGIN) + r".*?" + re.escape(DOSSIER_END), re.S)
    if not pattern.search(text):
        return text
    return pattern.sub(lambda _: dossier_table(pages), text)


def outputs() -> tuple[dict[str, str], list[str]]:
    pages = book.pages()
    concepts = book.load_data("concepts.toml").get("concept", [])
    notation = book.load_data("notation.toml").get("symbol", [])
    constants = book.load_data("constants.toml").get("constant", [])
    metrics = book.load_data("metrics.toml").get("metric", [])
    errors = validate(concepts, notation, constants, metrics, book.technologies(), book.bib_keys(), pages)
    files = {
        "appendices/concepts.qmd": concepts_page(concepts, pages),
        "appendices/notation.qmd": notation_page(notation),
        "appendices/constants.qmd": constants_page(constants),
        "appendices/people.qmd": people_page(pages),
    }
    index = building_alan_index(pages)
    if index is not None:
        files["building-alan/index.qmd"] = index
    return files, errors


def main(argv: list[str]) -> int:
    check = "--check" in argv
    files, errors = outputs()
    for error in errors:
        print(f"error: {error}", file=sys.stderr)
    stale = []
    for relative_path, content in files.items():
        path = book.ROOT / relative_path
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if check:
            stale.append(relative_path)
        else:
            path.write_text(content, encoding="utf-8")
            print(f"wrote {relative_path}")
    for relative_path in stale:
        print(f"error: {relative_path} is out of date; run python3 tools/generate.py", file=sys.stderr)
    return 1 if errors or stale else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
